db = {
    '\u0250': {
        'unicode': 'U+0250',
        'glyph': 'ɐ',
        'html': '&#592;',
        'unicode-name': 'Latin Small Letter Turned A',
        'ipa-description': 'Near-open central vowel',
        'ipa-no': '324',
        'type': 'vowel', 'backness': 'central', 'height': 'near-open'
    },
    '\u0251': {
        'unicode': 'U+0251',
        'glyph': 'ɑ',
        'html': '&#593;',
        'unicode-name': 'Latin Small Letter Alpha',
        'ipa-description': 'Open back unrounded vowel',
        'ipa-no': '305',
        'type': 'vowel', 'backness': 'back', 'height': 'open'
    },
    '\u0252': {
        'unicode': 'U+0252',
        'glyph': 'ɒ',
        'html': '&#594;',
        'unicode-name': 'Latin Small Letter Turned Alpha',
        'ipa-description': 'Open back rounded vowel',
        'ipa-no': '313',
        'type': 'vowel', 'backness': 'back', 'height': 'open'
    },
    '\u0253': {
        'unicode': 'U+0253',
        'glyph': 'ɓ',
        'html': '&#595;',
        'unicode-name': 'Latin Small Letter B with Hook',
        'ipa-description': 'Voiced bilabial implosive',
        'ipa-no': '160',
    },
    '\u0254': {
        'unicode': 'U+0254',
        'glyph': 'ɔ',
        'html': '&#596;',
        'unicode-name': 'Latin Small Letter Open O',
        'ipa-description': 'Open-mid back rounded vowel',
        'ipa-no': '306',
        'type': 'vowel', 'backness': 'back', 'height': 'open-mid'
    },
    '\u0255': {
        'unicode': 'U+0255',
        'glyph': 'ɕ',
        'html': '&#597;',
        'unicode-name': 'Latin Small Letter C with Curl',
        'ipa-description': 'Voiceless alveolo-palatal fricative',
        'ipa-no': '182',
    },
    '\u0256': {
        'unicode': 'U+0256',
        'glyph': 'ɖ',
        'html': '&#598;',
        'unicode-name': 'Latin Small Letter D with Tail',
        'ipa-description': 'Voiced retroflex plosive',
        'ipa-no': '106',
    },
    '\u0257': {
        'unicode': 'U+0257',
        'glyph': 'ɗ',
        'html': '&#599;',
        'unicode-name': 'Latin Small Letter D with Hook',
        'ipa-description': 'Voiced alveolar implosive',
        'ipa-no': '162',
    },
    '\u0258': {
        'unicode': 'U+0258',
        'glyph': 'ɘ',
        'html': '&#600;',
        'unicode-name': 'Latin Small Letter Reversed E',
        'ipa-description': 'Close-mid central unrounded vowel',
        'ipa-no': '397',
        'type': 'vowel', 'backness': 'central', 'height': 'close-mid'
    },
    '\u0259': {
        'unicode': 'U+0259',
        'glyph': 'ə',
        'html': '&#601;',
        'unicode-name': 'Latin Small Letter Schwa',
        'ipa-description': 'Mid central vowel',
        'ipa-no': '322',
        'type': 'vowel', 'backness': 'central', 'height': 'mid'
    },
    '\u025A': {
        'unicode': 'U+025A',
        'glyph': 'ɚ',
        'html': '&#602;',
        'unicode-name': 'Latin Small Letter Schwa with Hook',
        'ipa-description': 'Rhotacized Mid central vowel',
        'ipa-no': '327',
    },
    '\u025B': {
        'unicode': 'U+025B',
        'glyph': 'ɛ',
        'html': '&#603;',
        'unicode-name': 'Latin Small Letter Open E',
        'ipa-description': 'Open-mid front unrounded vowel',
        'ipa-no': '303',
        'type': 'vowel', 'backness': 'front', 'height': 'open-mid'
    },
    '\u025C': {
        'unicode': 'U+025C',
        'glyph': 'ɜ',
        'html': '&#604;',
        'unicode-name': 'Latin Small Letter Reversed Open E',
        'ipa-description': 'Open-mid central unrounded vowel',
        'ipa-no': '326',
        'type': 'vowel', 'backness': 'central', 'height': 'open-mid'
    },
    '\u025D': {
        'unicode': 'U+025D',
        'glyph': 'ɝ',
        'html': '&#605;',
        'unicode-name': 'Latin Small Letter Reversed Open E with Hook',
        'ipa-description': 'Rhotacized Open-mid central unrounded vowel',
        'ipa-no': None,
    },
    '\u025E': {
        'unicode': 'U+025E',
        'glyph': 'ɞ',
        'html': '&#606;',
        'unicode-name': 'Latin Small Letter Closed Reversed Open E',
        'ipa-description': 'Open-mid central rounded vowel',
        'ipa-no': '395',
        'type': 'vowel', 'backness': 'central', 'height': 'open-mid'
    },
    '\u025F': {
        'unicode': 'U+025F',
        'glyph': 'ɟ',
        'html': '&#607;',
        'unicode-name': 'Latin Small Letter Dotless J with Stroke',
        'ipa-description': 'Voiced palatal plosive',
        'ipa-no': '108',
    },
    '\u0260': {
        'unicode': 'U+0260',
        'glyph': 'ɠ',
        'html': '&#608;',
        'unicode-name': 'Latin Small Letter G with Hook',
        'ipa-description': 'Voiced velar implosive',
        'ipa-no': '166',
    },
    '\u0261': {
        'unicode': 'U+0261',
        'glyph': 'ɡ',
        'html': '&#609;',
        'unicode-name': 'Latin Small Letter Script G',
        'ipa-description': 'Voiced velar plosive',
        'ipa-no': '110',
    },
    '\u0262': {
        'unicode': 'U+0262',
        'glyph': 'ɢ',
        'html': '&#610;',
        'unicode-name': 'Latin Letter Small Capital G',
        'ipa-description': 'Voiced uvular plosive',
        'ipa-no': '112',
    },
    '\u0263': {
        'unicode': 'U+0263',
        'glyph': 'ɣ',
        'html': '&#611;',
        'unicode-name': 'Latin Small Letter Gamma',
        'ipa-description': 'Voiced velar fricative',
        'ipa-no': '141',
    },
    '\u0264': {
        'unicode': 'U+0264',
        'glyph': 'ɤ',
        'html': '&#612;',
        'unicode-name': 'Latin Small Letter Rams Horn',
        'ipa-description': 'Close-mid back unrounded vowel',
        'ipa-no': '315',
        'type': 'vowel', 'backness': 'back', 'height': 'close-mid'
    },
    '\u0265': {
        'unicode': 'U+0265',
        'glyph': 'ɥ',
        'html': '&#613;',
        'unicode-name': 'Latin Small Letter Turned H',
        'ipa-description': 'Labial-palatal approximant',
        'ipa-no': '171',
    },
    '\u0266': {
        'unicode': 'U+0266',
        'glyph': 'ɦ',
        'html': '&#614;',
        'unicode-name': 'Latin Small Letter H with Hook',
        'ipa-description': 'Voiced glottal fricative',
        'ipa-no': '147',
    },
    '\u0267': {
        'unicode': 'U+0267',
        'glyph': 'ɧ',
        'html': '&#615;',
        'unicode-name': 'Latin Small Letter Heng with Hook',
        'ipa-description': 'Swedish sj-sound. Similar to: Voiceless postalveolar fricative, Voiceless velar fricative',
        'ipa-no': '175',
    },
    '\u0268': {
        'unicode': 'U+0268',
        'glyph': 'ɨ',
        'html': '&#616;',
        'unicode-name': 'Latin Small Letter I with Stroke',
        'ipa-description': 'Close central unrounded vowel',
        'ipa-no': '317',
        'type': 'vowel', 'backness': 'central', 'height': 'close'
    },
    '\u0269': {
        'unicode': 'U+0269',
        'glyph': 'ɩ',
        'html': '&#617;',
        'unicode-name': 'Latin Small Letter Iota',
        'ipa-description': 'pre-1989 form of "ɪ" (obsolete)',
        'ipa-no': '399',
    },
    '\u026A': {
        'unicode': 'U+026A',
        'glyph': 'ɪ',
        'html': '&#618;',
        'unicode-name': 'Latin Letter Small Capital I',
        'ipa-description': 'Near-close near-front unrounded vowel',
        'ipa-no': '319',
        'type': 'vowel', 'backness': 'front', 'height': 'near-close'
    },
    '\u026B': {
        'unicode': 'U+026B',
        'glyph': 'ɫ',
        'html': '&#619;',
        'unicode-name': 'Latin Small Letter L with Middle Tilde',
        'ipa-description': 'Velar/pharyngeal Alveolar lateral approximant',
        'ipa-no': '209',
    },
    '\u026C': {
        'unicode': 'U+026C',
        'glyph': 'ɬ',
        'html': '&#620;',
        'unicode-name': 'Latin Small Letter L with Belt',
        'ipa-description': 'Voiceless alveolar lateral fricative',
        'ipa-no': '148',
    },
    '\u026D': {
        'unicode': 'U+026D',
        'glyph': 'ɭ',
        'html': '&#621;',
        'unicode-name': 'Latin Small Letter L with Retroflex Hook',
        'ipa-description': 'Retroflex lateral approximant',
        'ipa-no': '156',
    },
    '\u026E': {
        'unicode': 'U+026E',
        'glyph': 'ɮ',
        'html': '&#622;',
        'unicode-name': 'Latin Small Letter Lezh',
        'ipa-description': 'Voiced alveolar lateral fricative',
        'ipa-no': '149',
    },
    '\u026F': {
        'unicode': 'U+026F',
        'glyph': 'ɯ',
        'html': '&#623;',
        'unicode-name': 'Latin Small Letter Turned M',
        'ipa-description': 'Close back unrounded vowel',
        'ipa-no': '316',
        'type': 'vowel', 'backness': 'back', 'height': 'close'
    },
    '\u0270': {
        'unicode': 'U+0270',
        'glyph': 'ɰ',
        'html': '&#624;',
        'unicode-name': 'Latin Small Letter Turned M with Long Leg',
        'ipa-description': 'Velar approximant',
        'ipa-no': '154',
    },
    '\u0271': {
        'unicode': 'U+0271',
        'glyph': 'ɱ',
        'html': '&#625;',
        'unicode-name': 'Latin Small Letter M with Hook',
        'ipa-description': 'Labiodental nasal',
        'ipa-no': '115',
    },
    '\u0272': {
        'unicode': 'U+0272',
        'glyph': 'ɲ',
        'html': '&#626;',
        'unicode-name': 'Latin Small Letter N with Left Hook',
        'ipa-description': 'Palatal nasal',
        'ipa-no': '118',
    },
    '\u0273': {
        'unicode': 'U+0273',
        'glyph': 'ɳ',
        'html': '&#627;',
        'unicode-name': 'Latin Small Letter N with Retroflex Hook',
        'ipa-description': 'Retroflex nasal',
        'ipa-no': '117',
    },
    '\u0274': {
        'unicode': 'U+0274',
        'glyph': 'ɴ',
        'html': '&#628;',
        'unicode-name': 'Latin Letter Small Capital N',
        'ipa-description': 'Uvular nasal',
        'ipa-no': '120',
    },
    '\u0275': {
        'unicode': 'U+0275',
        'glyph': 'ɵ',
        'html': '&#629;',
        'unicode-name': 'Latin Small Letter Barred O',
        'ipa-description': 'Close-mid central rounded vowel',
        'ipa-no': '323',
        'type': 'vowel', 'backness': 'central', 'height': 'close-mid'
    },
    '\u0276': {
        'unicode': 'U+0276',
        'glyph': 'ɶ',
        'html': '&#630;',
        'unicode-name': 'Latin Letter Small Capital OE',
        'ipa-description': 'Open front rounded vowel',
        'ipa-no': '312',
        'type': 'vowel', 'backness': 'front', 'height': 'open'
    },
    '\u0277': {
        'unicode': 'U+0277',
        'glyph': 'ɷ',
        'html': '&#631;',
        'unicode-name': 'Latin Small Letter Closed Omega',
        'ipa-description': 'pre-1989 form of "ʊ" (obsolete)',
        'ipa-no': '398',
    },
    '\u0278': {
        'unicode': 'U+0278',
        'glyph': 'ɸ',
        'html': '&#632;',
        'unicode-name': 'Latin Small Letter Phi',
        'ipa-description': 'Voiceless bilabial fricative',
        'ipa-no': '126',
    },
    '\u0279': {
        'unicode': 'U+0279',
        'glyph': 'ɹ',
        'html': '&#633;',
        'unicode-name': 'Latin Small Letter Turned R',
        'ipa-description': 'Alveolar approximant',
        'ipa-no': '151',
    },
    '\u027A': {
        'unicode': 'U+027A',
        'glyph': 'ɺ',
        'html': '&#634;',
        'unicode-name': 'Latin Small Letter Turned R with Long Leg',
        'ipa-description': 'Alveolar lateral flap',
        'ipa-no': '181',
    },
    '\u027B': {
        'unicode': 'U+027B',
        'glyph': 'ɻ',
        'html': '&#635;',
        'unicode-name': 'Latin Small Letter Turned R with Hook',
        'ipa-description': 'Retroflex approximant',
        'ipa-no': '152',
    },
    '\u027C': {
        'unicode': 'U+027C',
        'glyph': 'ɼ',
        'html': '&#636;',
        'unicode-name': 'Latin Small Letter R with Long Leg',
        'ipa-description': 'Alveolar trill',
        'ipa-no': '206',
    },
    '\u027D': {
        'unicode': 'U+027D',
        'glyph': 'ɽ',
        'html': '&#637;',
        'unicode-name': 'Latin Small Letter R with Tail',
        'ipa-description': 'Retroflex flap',
        'ipa-no': '125',
    },
    '\u027E': {
        'unicode': 'U+027E',
        'glyph': 'ɾ',
        'html': '&#638;',
        'unicode-name': 'Latin Small Letter R with Fishhook',
        'ipa-description': 'Alveolar tap',
        'ipa-no': '124',
    },
    '\u027F': {
        'unicode': 'U+027F',
        'glyph': 'ɿ',  # not working! gets converted to None
        'html': '&#639;',
        'unicode-name': 'Latin Small Letter Reversed R with Fishhook',
        'ipa-description': 'Syllabic voiced alveolar fricative (Sinologist usage)',
        'glyph': None,
        'sinology': True,
    },
    '\u0280': {
        'unicode': 'U+0280',
        'glyph': 'ʀ',
        'html': '&#640;',
        'unicode-name': 'Latin Letter Small Capital R',
        'ipa-description': 'Uvular trill',
        'ipa-no': '123',
    },
    '\u0281': {
        'unicode': 'U+0281',
        'glyph': 'ʁ',
        'html': '&#641;',
        'unicode-name': 'Latin Letter Small Capital Inverted R',
        'ipa-description': 'Voiced uvular fricative',
        'ipa-no': '143',
    },
    '\u0282': {
        'unicode': 'U+0282',
        'glyph': 'ʂ',
        'html': '&#642;',
        'unicode-name': 'Latin Small Letter S with Hook',
        'ipa-description': 'Voiceless retroflex fricative',
        'ipa-no': '136',
    },
    '\u0283': {
        'unicode': 'U+0283',
        'glyph': 'ʃ',
        'html': '&#643;',
        'unicode-name': 'Latin Small Letter Esh',
        'ipa-description': 'Voiceless postalveolar fricative',
        'ipa-no': '134',
    },
    '\u0284': {
        'unicode': 'U+0284',
        'glyph': 'ʄ',
        'html': '&#644;',
        'unicode-name': 'Latin Small Letter Dotless J with Stroke and Hook',
        'ipa-description': 'Voiced palatal implosive',
        'ipa-no': '164',
    },
    '\u0285': {
        'unicode': 'U+0285',
        'glyph': 'ʅ',  # not working! gets converted to None
        'html': '&#645;',
        'unicode-name': 'Latin Small Letter Squat Reversed Esh',
        'ipa-description': 'Syllabic voiced retroflex fricative (Sinologist usage)',
        'glyph': None,
        'sinology': True,
    },
    '\u0286': {
        'unicode': 'U+0286',
        'glyph': 'ʆ',
        'html': '&#646;',
        'unicode-name': 'Latin Small Letter Esh with Curl',
        'ipa-description': 'Voiceless alveolo-palatal fricative (obsolete)',
        'ipa-no': '204',
    },
    '\u0287': {
        'unicode': 'U+0287',
        'glyph': 'ʇ',
        'html': '&#647;',
        'unicode-name': 'Latin Small Letter Turned T',
        'ipa-description': 'Dental click (obsolete)',
        'ipa-no': '201',
    },
    '\u0288': {
        'unicode': 'U+0288',
        'glyph': 'ʈ',
        'html': '&#648;',
        'unicode-name': 'Latin Small Letter T with Retroflex Hook',
        'ipa-description': 'Voiceless retroflex plosive',
        'ipa-no': '105',
    },
    '\u0289': {
        'unicode': 'U+0289',
        'glyph': 'ʉ',
        'html': '&#649;',
        'unicode-name': 'Latin Small Letter U Bar',
        'ipa-description': 'Close central rounded vowel',
        'ipa-no': '318',
        'type': 'vowel', 'backness': 'central', 'height': 'close'
    },
    '\u028A': {
        'unicode': 'U+028A',
        'glyph': 'ʊ',
        'html': '&#650;',
        'unicode-name': 'Latin Small Letter Upsilon',
        'ipa-description': 'near-close near-back rounded vowel',
        'ipa-no': '321',
        'type': 'vowel', 'backness': 'back', 'height': 'near-close'
    },
    '\u028B': {
        'unicode': 'U+028B',
        'glyph': 'ʋ',
        'html': '&#651;',
        'unicode-name': 'Latin Small Letter V with Hook',
        'ipa-description': 'Labiodental approximant',
        'ipa-no': '150',
    },
    '\u028C': {
        'unicode': 'U+028C',
        'glyph': 'ʌ',
        'html': '&#652;',
        'unicode-name': 'Latin Small Letter Turned V',
        'ipa-description': 'Open-mid back unrounded vowel',
        'ipa-no': '314',
        'type': 'vowel', 'backness': 'back', 'height': 'open-mid'
    },
    '\u028D': {
        'unicode': 'U+028D',
        'glyph': 'ʍ',
        'html': '&#653;',
        'unicode-name': 'Latin Small Letter Turned W',
        'ipa-description': 'Voiceless labiovelar approximant',
        'ipa-no': '169',
    },
    '\u028E': {
        'unicode': 'U+028E',
        'glyph': 'ʎ',
        'html': '&#654;',
        'unicode-name': 'Latin Small Letter Turned Y',
        'ipa-description': 'Palatal lateral approximant',
        'ipa-no': '157',
    },
    '\u028F': {
        'unicode': 'U+028F',
        'glyph': 'ʏ',
        'html': '&#655;',
        'unicode-name': 'Latin Letter Small Capital Y',
        'ipa-description': 'Near-close near-front rounded vowel',
        'ipa-no': '320',
        'type': 'vowel', 'backness': 'front', 'height': 'near-close'
    },
    '\u0290': {
        'unicode': 'U+0290',
        'glyph': 'ʐ',
        'html': '&#656;',
        'unicode-name': 'Latin Small Letter Z with Retroflex Hook',
        'ipa-description': 'Voiced retroflex fricative',
        'ipa-no': '137',
    },
    '\u0291': {
        'unicode': 'U+0291',
        'glyph': 'ʑ',
        'html': '&#657;',
        'unicode-name': 'Latin Small Letter Z with Curl',
        'ipa-description': 'Voiced alveolo-palatal fricative',
        'ipa-no': '183',
    },
    '\u0292': {
        'unicode': 'U+0292',
        'glyph': 'ʒ',
        'html': '&#658;',
        'unicode-name': 'Latin Small Letter Ezh',
        'ipa-description': 'Voiced postalveolar fricative',
        'ipa-no': '135',
    },
    '\u0293': {
        'unicode': 'U+0293',
        'glyph': 'ʓ',
        'html': '&#659;',
        'unicode-name': 'Latin Small Letter Ezh with Curl',
        'ipa-description': 'Voiced alveolo-palatal fricative (obsolete)',
        'ipa-no': '205',
    },
    '\u0294': {
        'unicode': 'U+0294',
        'glyph': 'ʔ',
        'html': '&#660;',
        'unicode-name': 'Latin Letter Glottal Stop',
        'ipa-description': 'Glottal stop',
        'ipa-no': '113',
    },
    '\u0295': {
        'unicode': 'U+0295',
        'glyph': 'ʕ',
        'html': '&#661;',
        'unicode-name': 'Latin Letter Pharyngeal Voiced Fricative',
        'ipa-description': 'Voiced pharyngeal fricative',
        'ipa-no': '145',
    },
    '\u0296': {
        'unicode': 'U+0296',
        'glyph': 'ʖ',
        'html': '&#662;',
        'unicode-name': 'Latin Letter Inverted Glottal Stop',
        'ipa-description': 'Alveolar lateral click (obsolete)',
        'ipa-no': '203',
    },
    '\u0297': {
        'unicode': 'U+0297',
        'glyph': 'ʗ',
        'html': '&#663;',
        'unicode-name': 'Latin Letter Stretched C',
        'ipa-description': 'Postalveolar click (obsolete)',
        'ipa-no': '202',
    },
    '\u0298': {
        'unicode': 'U+0298',
        'glyph': 'ʘ',
        'html': '&#664;',
        'unicode-name': 'Latin Letter Bilabial Click',
        'ipa-description': 'Bilabial click',
        'ipa-no': '176',
    },
    '\u0299': {
        'unicode': 'U+0299',
        'glyph': 'ʙ',
        'html': '&#665;',
        'unicode-name': 'Latin Letter Small Capital B',
        'ipa-description': 'Bilabial trill',
        'ipa-no': '121',
    },
    '\u029A': {
        'unicode': 'U+029A',
        'glyph': 'ʚ',
        'html': '&#666;',
        'unicode-name': 'Latin Small Letter Closed Open E',
        'ipa-description': 'A mistake for [œ]',
        'ipa-no': '396',
    },
    '\u029B': {
        'unicode': 'U+029B',
        'glyph': 'ʛ',
        'html': '&#667;',
        'unicode-name': 'Latin Letter Small Capital G with Hook',
        'ipa-description': 'Voiced uvular implosive',
        'ipa-no': '168',
    },
    '\u029C': {
        'unicode': 'U+029C',
        'glyph': 'ʜ',
        'html': '&#668;',
        'unicode-name': 'Latin Letter Small Capital H',
        'ipa-description': 'Voiceless epiglottal fricative',
        'ipa-no': '172',
    },
    '\u029D': {
        'unicode': 'U+029D',
        'glyph': 'ʝ',
        'html': '&#669;',
        'unicode-name': 'Latin Small Letter J with Crossed Tail',
        'ipa-description': 'Voiced palatal fricative',
        'ipa-no': '139',
    },
    '\u029E': {
        'unicode': 'U+029E',
        'glyph': 'ʞ',
        'html': '&#670;',
        'unicode-name': 'Latin Small Letter Turned K',
        'ipa-description': 'Velar click (obsolete)',
        'ipa-no': '291',
    },
    '\u029F': {
        'unicode': 'U+029F',
        'glyph': 'ʟ',
        'html': '&#671;',
        'unicode-name': 'Latin Letter Small Capital L',
        'ipa-description': 'Velar lateral approximant',
        'ipa-no': '158',
    },
    '\u02A0': {
        'unicode': 'U+02A0',
        'glyph': 'ʠ',
        'html': '&#672;',
        'unicode-name': 'Latin Small Letter Q with Hook',
        'ipa-description': '"Voiceless" uvular implosive (obsolete)',
        'ipa-no': '167',
    },
    '\u02A1': {
        'unicode': 'U+02A1',
        'glyph': 'ʡ',
        'html': '&#673;',
        'unicode-name': 'Latin Letter Glottal Stop with Stroke',
        'ipa-description': 'Epiglottal plosive',
        'ipa-no': '173',
    },
    '\u02A2': {
        'unicode': 'U+02A2',
        'glyph': 'ʢ',
        'html': '&#674;',
        'unicode-name': 'Latin Letter Reversed Glottal Stop with Stroke',
        'ipa-description': 'Voiced epiglottal fricative',
        'ipa-no': '174',
    },
    '\u02A3': {
        'unicode': 'U+02A3',
        'glyph': 'ʣ',
        'html': '&#675;',
        'unicode-name': 'Latin Small Letter DZ Digraph',
        'ipa-description': 'Voiced alveolar affricate (obsolete)',
        'ipa-no': '212',
    },
    '\u02A4': {
        'unicode': 'U+02A4',
        'glyph': 'ʤ',
        'html': '&#676;',
        'unicode-name': 'Latin Small Letter Dezh Digraph',
        'ipa-description': 'Voiced postalveolar affricate (obsolete)',
        'ipa-no': '214',
    },
    '\u02A5': {
        'unicode': 'U+02A5',
        'glyph': 'ʥ',
        'html': '&#677;',
        'unicode-name': 'Latin Small Letter DZ Digraph with Curl',
        'ipa-description': 'Voiced alveolo-palatal affricate (obsolete)',
        'ipa-no': '216',
    },
    '\u02A6': {
        'unicode': 'U+02A6',
        'glyph': 'ʦ',
        'html': '&#678;',
        'unicode-name': 'Latin Small Letter TS Digraph',
        'ipa-description': 'Voiceless alveolar affricate (obsolete)',
        'ipa-no': '211',
    },
    '\u02A7': {
        'unicode': 'U+02A7',
        'glyph': 'ʧ',
        'html': '&#679;',
        'unicode-name': 'Latin Small Letter Tesh Digraph',
        'ipa-description': 'Voiceless postalveolar affricate (obsolete)',
        'ipa-no': '213',
    },
    '\u02A8': {
        'unicode': 'U+02A8',
        'glyph': 'ʨ',
        'html': '&#680;',
        'unicode-name': 'Latin Small Letter TC Digraph with Curl',
        'ipa-description': 'Voiceless alveolo-palatal affricate (obsolete)',
        'ipa-no': '215',
    },
    '\u02A9': {
        'unicode': 'U+02A9',
        'glyph': 'ʩ',
        'html': '&#681;',
        'unicode-name': 'Latin Small Letter Feng Digraph',
        'ipa-description': 'velopharyngeal fricative',
        'ipa-no': '602',
        'disordered-speech': True,
    },
    '\u02AA': {
        'unicode': 'U+02AA',
        'glyph': 'ʪ',
        'html': '&#682;',
        'unicode-name': 'Latin Small Letter LS Digraph',
        'ipa-description': 'Voiceless grooved lateral alveolar fricative',
        'ipa-no': '603',
        'disordered-speech': True,
    },
    '\u02AB': {
        'unicode': 'U+02AB',
        'glyph': 'ʫ',
        'html': '&#683;',
        'unicode-name': 'Latin Small Letter LZ Digraph',
        'ipa-description': 'voiced grooved lateral alveolar fricative',
        'ipa-no': '604',
        'disordered-speech': True,
    },
    '\u02AC': {
        'unicode': 'U+02AC',
        'glyph': 'ʬ',
        'html': '&#684;',
        'unicode-name': 'Latin Letter Bilabial Percussive',
        'ipa-description': 'Bilabial percussive',
        'ipa-no': None,
        'disordered-speech': True,
    },
    '\u02AD': {
        'unicode': 'U+02AD',
        'glyph': 'ʭ',
        'html': '&#685;',
        'unicode-name': 'Latin Letter Bidental Percussive',
        'ipa-description': 'Bidental percussive',
        'ipa-no': '601',
        'disordered-speech': True,
    },
    '\u02AE': {
        'unicode': 'U+02AE',
        'glyph': 'ʮ',
        'html': '&#686;',
        'unicode-name': 'Latin Small Letter Turned H with Fishhook',
        'ipa-description': 'Syllabic labialized voiced alveolar fricative (Sinologist usage)',
        'ipa-no': None,
        'sinology': True,
    },
    '\u02AF': {
        'unicode': 'U+02AF',
        'glyph': 'ʯ',
        'html': '&#687;',
        'unicode-name': 'Latin Small Letter Turned H with Fishhook and Tail',
        'ipa-description': 'Syllabic labialized voiced retroflex fricative (Sinologist usage)',
        'ipa-no': None,
        'sinology': True,
    },
    '\u0069': {
        'unicode': 'U+0069',
        'glyph': 'i',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'front', 'height': 'close'
    },
    '\u0079': {
        'unicode': 'U+0079',
        'glyph': 'y',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'front', 'height': 'close'
    },
    '\u0065': {
        'unicode': 'U+0065',
        'glyph': 'e',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'front', 'height': 'close-mid'
    },
    '\u00F8': {
        'unicode': 'U+00F8',
        'glyph': 'ø',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'front', 'height': 'close-mid'
    },
    '\u0065\u031E': {
        'unicode': 'U+0065 U+031E',
        'glyph': 'e̞',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'front', 'height': 'mid'
    },
    '\u00F8\u031E': {
        'unicode': 'U+00F8 U+031E',
        'glyph': 'ø̞',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'front', 'height': 'mid'
    },
    '\u0153': {
        'unicode': 'U+0153',
        'glyph': 'œ',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'front', 'height': 'open-mid'
    },
    '\u00E6': {
        'unicode': 'U+00E6',
        'glyph': 'æ',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'front', 'height': 'near-open'
    },
    '\u0061': {
        'unicode': 'U+0061',
        'glyph': 'a',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'front', 'height': 'open'
    },
    '\u0061\u0308': {
        'unicode': 'U+0061 U+0308',
        'glyph': 'ä',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'central', 'height': 'open'
    },
    '\u0075': {
        'unicode': 'U+0075',
        'glyph': 'u',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'back', 'height': 'close'
    },
    '\u006F': {
        'unicode': 'U+006F',
        'glyph': 'o',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'back', 'height': 'close-mid'
    },
    '\u0264\u031E': {
        'unicode': 'U+0264 U+031E',
        'glyph': 'ɤ̞',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'back', 'height': 'mid'
    },
    '\u006F\u031E': {
        'unicode': 'U+006F U+031E',
        'glyph': 'o̞',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'back', 'height': 'mid'
    },
    '\u026A\u0308': {
        'unicode': 'U+026A U+0308',
        'glyph': 'ɪ̈',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'central', 'height': 'near-close'
    },
    '\u028A\u0308': {
        'unicode': 'U+028A U+0308',
        'glyph': 'ʊ̈',
        # 'html': '',
        # 'unicode-name': '',
        # 'ipa-description': '',
        # 'ipa-no': '',
        'type': 'vowel', 'backness': 'central', 'height': 'near-close'
    },
}
